server:
  port: 7979
info:
    version: @project.version@
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://master:8761/eureka/,http://slave:8762/eureka/
#####设置日志######
logging:
   file: ..//logs//hystrix.log
   level:
     root: info